### ISSUE TITLE
generate silence wav

### ISSUE THREAD

**Issue by martin3252** [dtx525942103/vits_chinese#6]
Thanks for sharing this repo, I met a problem here, 
I followed your instruction without any modify and after training 120k steps, I generated a whole silence wav by vit_string.py
Is it normal or did i anything wrong?

**Comment by jmaxzh** [comment]
> Thanks for sharing this repo, I met a problem here, I followed your instruction without any modify and after training 120k steps, I generated a whole silence wav by vit_string.py Is it normal or did i anything wrong?

I also met the same problem, how to solve this problem
